
import { jsPDF } from "jspdf";
import { loadFontAsBase64 } from "./loadFontAsBase64";

// generated by chatGPT
export async function generateResultsPdf(results) {
  const { title, date, categoriesResults } = results;
  const doc = new jsPDF({ unit: "pt", format: "a4" });

  const base64 = await loadFontAsBase64('/fonts/PTSans-Regular.ttf');
  const base64Bold = await loadFontAsBase64('/fonts/PTSans-Bold.ttf');
  const base64Italic = await loadFontAsBase64('/fonts/PTSans-Italic.ttf');

  doc.addFileToVFS('PTSans-Regular-normal.ttf', base64);
  doc.addFont('PTSans-Regular-normal.ttf', 'PTSans', 'normal');

  doc.addFileToVFS('PTSans-Bold-bold.ttf', base64Bold);
  doc.addFont('PTSans-Bold-bold.ttf', 'PTSans', 'bold');

  doc.addFileToVFS('PTSans-Italic-italic.ttf', base64Italic);
  doc.addFont('PTSans-Italic-italic.ttf', 'PTSans', 'italic');
  
  doc.setFont("PTSans", 'normal'); 

  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();


  const margin = { top: 48, right: 48, bottom: 64, left: 48 };

  const titleSize = 16;
  const dateSize = 11;
  const catSize = 13;
  const itemSize = 11;

  const lineGap = 6;
  const catTitleGap = 10;
  const catBlockGap = 12;
  const dateBlockGap = 18;

  // Відступи навколо розділювача (збільшені +6)
  const sepTopGap = 22;
  const sepBotGap = 22;

  const sepColorGray = 60;
  const sepLineWidth = 1;

  let y = margin.top;
  let isFirstPage = true;

  function drawHeader({ showDate }) {
    doc.setFont("PTSans", "bold");
    doc.setFontSize(titleSize);
    doc.text(title, pageWidth / 2, y, { align: "center" });
    y += titleSize + 4;

    if (showDate) {
      doc.setFont("PTSans", "normal");
      doc.setFontSize(dateSize);
      doc.text(date, pageWidth - margin.right, y, { align: "right" });
      y += dateBlockGap;
    } else {
      y += 8;
    }
  }

  function ensureSpace(neededHeight) {
    if (y + neededHeight > pageHeight - margin.bottom) {
      doc.addPage();
      y = margin.top;
      isFirstPage = false;
      drawHeader({ showDate: false });

      // 🟢 Відновлюємо стиль для списків (regular, 11pt)
      doc.setFont("PTSans", "normal");
      doc.setFontSize(itemSize);
    }
  }

  // --- Контент ---
  drawHeader({ showDate: true });

  categoriesResults.forEach((cat, catIndex) => {
    const catMaxWidth = pageWidth - margin.left - margin.right;
    doc.setFont("PTSans", "bold");
    doc.setFontSize(catSize);

    const catLines = doc.splitTextToSize(cat.name, catMaxWidth);
    const catBlockHeight = catLines.length * (catSize + 2);
    ensureSpace(catBlockHeight + catTitleGap);

    catLines.forEach(line => {
      doc.text(line, margin.left, y);
      y += catSize + 2;
    });
    y += catTitleGap;

    // Учасники завжди однаковим стилем (звичайний regular)
    doc.setFont("PTSans", "normal");
    doc.setFontSize(itemSize);

    cat.results.forEach((athlete, idx) => {
      const text = `${idx + 1}. ${athlete}`;
      const itemLines = doc.splitTextToSize(text, catMaxWidth - 16);
      const itemHeight = itemLines.length * (itemSize + 2);

      ensureSpace(itemHeight + lineGap);

      const itemX = margin.left + 12;
      itemLines.forEach(line => {
        doc.text(line, itemX, y);
        y += itemSize + 2;
      });

      y += lineGap;
    });

    y += catBlockGap;

    // Розділювач
    if (catIndex < categoriesResults.length - 1) {
      ensureSpace(sepTopGap + sepLineWidth + sepBotGap);
      y += sepTopGap;

      doc.setDrawColor(sepColorGray);
      doc.setLineWidth(sepLineWidth);
      doc.line(margin.left, y, pageWidth - margin.right, y);

      y += sepBotGap;
    }
  });

  // --- Футер ---
  const pageCount = doc.getNumberOfPages();
  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i);

    // Лінія футера (на 6pt вище від тексту)
    doc.setDrawColor(180);
    doc.setLineWidth(0.5);
    const footerY = pageHeight - margin.bottom + 16;
    doc.line(margin.left, footerY - 16, pageWidth - margin.right, footerY - 16); // було -10 → стало -16

    // Нумерація по центру
    doc.setFont("PTSans", "italic");
    doc.setFontSize(10);
    const footerText = `Page ${i} of ${pageCount}`;
    doc.text(footerText, pageWidth / 2, footerY, { align: "center" });

    // Маленький текст праворуч
    doc.setFont("PTSans", "normal");
    doc.setFontSize(9);
    doc.text("made with ARM-GRID", pageWidth - margin.right, footerY, { align: "right" });
  }

  doc.save("tournament_results.pdf");

}